version: '3.3'
services:
  server:
    env_file: ./config/dev.env
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 80:3000
      - 443:443 # https
    links:
      - db
  db:
    container_name: mongo
    image: mongo:4
    restart: always
    ports:
      - 27017:27017

