version: '3.8'
services:
  server:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
      #- /app/node_modules
      - ~/.ssh/:/root/.ssh
    ports:
      - 80:3000
      - 443:443
    links:
      - db
    #secrets:
    #  - secret_ssh_key
  db:
    container_name: mongo
    image: mongo:4
    restart: always
    ports:
      - 27017:27017
#secrets:
#  secret_ssh_key:
#    file: ~/.ssh/id_rsa
