[build]
  command = "yarn build"
  publish = "dist/client/"

[functions]
  directory = "dist/server/functions/"

[[redirects]]
  from = "/uranio/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [dev]
    framework = "#custom"
    command = "yarn dev:client --native"
    targetPort = 3000
    debug = true
    port = 8888
    publish = "dist"
