[build]
  command = "yarn build"
  publish = "dist/client/"

[functions]
  directory = "dist/server/functions/"

[[redirects]]
  from = "/uranio/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [dev]
    framework = "#custom"
    command = "yarn dev:client --native --inside_ntl"
    targetPort = 5555
    debug = true
    port = 7777
    publish = "dist"
