/**
 *
 * Autogenerated book from urn-cli
 *
 */
export const api_book = {
	superuser: {
		api: {
			url: "/superusers",
		},
	},
	user: {
		api: {
			url: "/users",
		},
	},
	group: {
		api: {
			url: "/groups",
		},
	},
	error: {
		api: {
			url: "/errors",
		},
	},
	request: {
		api: {
			url: "/requests",
		},
	},
} as const;
