/**
 *
 * Autogenerated book from urn-cli
 *
 */
import * as types_202516519 from "../../lib/cln/types";
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
		},
	},
	user: {
		dock: {
			url: "/users",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
		},
	},
	mykart: {
		dock: {
			url: "mykarts",
			routes: {
				myroute: {
					method: types_202516519.RouteMethod.GET,
					action: types_202516519.AuthAction.READ,
					url: "/myroute",
					query: ["myq"],
				},
			},
		},
	},
	kart: {
		dock: {
			url: "/karts",
			routes: {
				mycustom: {
					url: "/c/:id/:date",
					query: ["sick"],
					action: types_202516519.AuthAction.READ,
					method: types_202516519.RouteMethod.GET,
				},
			},
		},
	},
} as const;
