/**
 *
 * Autogenerated book from urn-cli
 *
 */
import uranio from '../../lib/client';
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
		},
	},
	user: {
		dock: {
			url: "/users",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
			routes: {
				mycustom: {
					url: '/:id/:date',
					query: ['sick'],
					action: uranio.types.AuthAction.READ,
					method: uranio.types.RouteMethod.GET
				}
			}
		},
	},
	kart: {
		dock: {
			url: "/karts",
			routes: {
				mycustom: {
					url: '/c/:id/:date',
					query: ['sick'],
					action: uranio.types.AuthAction.READ,
					method: uranio.types.RouteMethod.GET
				}
			}
		},
	}
} as const;
