/**
 *
 * Autogenerated book from urn-cli
 *
 */

import uranio from "uranio";
export const atom_book = {
	superuser: {
		authenticate: true,
		plural: "superusers",
		security: {
			type: uranio.types.BookSecurityType.UNIFORM,
			_r: uranio.types.BookPermissionType.NOBODY,
		},
		properties: {
			email: {
				type: uranio.types.BookPropertyType.EMAIL,
				label: "Email",
				unique: true,
				on_error: () => {
					return "email@email.com";
				},
			},
			password: {
				type: uranio.types.BookPropertyType.ENCRYPTED,
				label: "Password",
				hidden: true,
			},
			groups: {
				type: uranio.types.BookPropertyType.ATOM_ARRAY,
				atom: "group",
				label: "Groups",
				optional: true,
			},
		},
	},
	user: {
		authenticate: true,
		plural: "users",
		security: {
			type: uranio.types.BookSecurityType.GRANULAR,
		},
		properties: {
			email: {
				type: uranio.types.BookPropertyType.EMAIL,
				label: "Email",
				unique: true,
			},
			password: {
				type: uranio.types.BookPropertyType.ENCRYPTED,
				label: "Password",
				hidden: true,
			},
			groups: {
				type: uranio.types.BookPropertyType.ATOM_ARRAY,
				atom: "group",
				label: "Groups",
				optional: true,
			},
		},
	},
	group: {
		plural: "groups",
		properties: {
			name: {
				type: uranio.types.BookPropertyType.TEXT,
				unique: true,
				label: "Name",
			},
		},
	},
	media: {
		plural: "media",
		properties: {
			src: {
				type: uranio.types.BookPropertyType.TEXT,
				label: "SRC",
			},
			filename: {
				primary: true,
				type: uranio.types.BookPropertyType.TEXT,
				label: "Filename",
			},
			type: {
				type: uranio.types.BookPropertyType.TEXT,
				label: "Filetype",
			},
			size: {
				type: uranio.types.BookPropertyType.INTEGER,
				label: "Size (byte)",
				validation: {
					min: 0,
				},
			},
			width: {
				optional: true,
				type: uranio.types.BookPropertyType.INTEGER,
				label: "Width",
				validation: {
					min: 0,
				},
			},
			height: {
				optional: true,
				type: uranio.types.BookPropertyType.INTEGER,
				label: "Height",
				validation: {
					min: 0,
				},
			},
		},
	},
	customer: {
		plural: "customers",
		security: {
			type: uranio.types.BookSecurityType.UNIFORM,
			_w: uranio.types.BookPermissionType.PUBLIC,
		},
		properties: {
			first_name: {
				sortable: false,
				type: uranio.types.BookPropertyType.TEXT,
				label: "First name",
			},
			last_name: {
				type: uranio.types.BookPropertyType.TEXT,
				label: "Last name",
				is_title: true,
			},
		},
	},
	mykart: {
		security: {
			type: uranio.types.BookSecurityType.UNIFORM,
			_w: uranio.types.BookPermissionType.PUBLIC,
		},
		plural: "mykarts",
		properties: {
			title: {
				is_title: true,
				type: uranio.types.BookPropertyType.TEXT,
				// label: `${some}-titless`
				label: `titless`,
				style: {
					full_width: true,
					classes: "custom-class-name",
				},
			},
		},
		// bll: () => {
		//   console.log(some + `s`);
		//   return new MYBLL();
		// }
	},
	product: {
		security: {
			type: uranio.types.BookSecurityType.UNIFORM,
			_w: uranio.types.BookPermissionType.PUBLIC,
		},
		properties: {
			title: {
				is_title: true,
				primary: true,
				type: uranio.types.BookPropertyType.TEXT,
				label: "Title",
				style: {
					full_width: true,
				},
				validation: {
					alphanum: true,
					contain_digit: false,
					max: 7,
				},
				on_error: () => "TITLE",
			},
			description: {
				primary: true,
				type: uranio.types.BookPropertyType.LONG_TEXT,
				label: "Description",
				style: {
					full_width: true,
				},
			},
			kart: {
				primary: true,
				type: uranio.types.BookPropertyType.ATOM,
				label: "Kart",
				atom: "mykart",
				optional: true,
			},
			users: {
				type: uranio.types.BookPropertyType.ATOM_ARRAY,
				label: "Users",
				atom: "user",
				optional: true,
			},
			active: {
				primary: true,
				type: uranio.types.BookPropertyType.BINARY,
				label: "Active",
			},
			email: {
				primary: true,
				type: uranio.types.BookPropertyType.EMAIL,
				label: "Email",
			},
			password: {
				type: uranio.types.BookPropertyType.ENCRYPTED,
				label: "Password",
			},
			type: {
				primary: true,
				type: uranio.types.BookPropertyType.ENUM_NUMBER,
				label: "Type Code",
				values: [1, 2, 3],
				optional: true,
				default: 1,
			},
			type_str: {
				primary: true,
				type: uranio.types.BookPropertyType.ENUM_STRING,
				label: "Type String",
				values: ["Red", "Green", "Blue"],
				optional: true,
			},
			price: {
				primary: true,
				type: uranio.types.BookPropertyType.FLOAT,
				label: "Price",
				validation: {
					min: 10,
				},
			},
			unit: {
				primary: true,
				type: uranio.types.BookPropertyType.INTEGER,
				label: "Unit",
				// validation: {
				//   min: 0,
				//   max: 10
				// }
			},
			categories: {
				type: uranio.types.BookPropertyType.SET_NUMBER,
				label: "Categories",
				// validation: {
				//   length: 2
				// },
				default: [1, 2],
				optional: true,
			},
			categories_str: {
				type: uranio.types.BookPropertyType.SET_STRING,
				label: "Categories string",
				optional: true,
			},
			pub_date: {
				type: uranio.types.BookPropertyType.TIME,
				label: "Pub date",
				// validation: {
				//   min: new Date('2011-03-08')
				// }
			},
		},
	},
} as const;
