/**
 *
 * Autogenerated book from urn-cli
 *
 */

import uranio from "uranio";
export const bll_book = {
	superuser: {},
	user: {},
	group: {},
	media: {
		bll: {
			class: (passport?: uranio.types.Passport) => {
				return uranio.bll.media.create(passport);
			},
		},
	},
	customer: {},
	mykart: {
		// bll: () => {
		//   console.log(some + `s`);
		//   return new MYBLL();
		// }
	},
	product: {},
} as const;
