/**
 *
 * Autogenerated book from urn-cli
 *
 */

export const bll_book = {
	superuser: {},
	user: {},
	group: {},
	media: {},
	setting: {},
	error: {},
	request: {},
	customer: {},
	mykart: {
		// bll: () => {
		//   console.log(some + `s`);
		//   return new MYBLL();
		// }
	},
	product: {},
} as const;
