/**
 *
 * Autogenerated book from urn-cli
 *
 */
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
			auth_url: "/superauth",
		},
	},
	user: {
		dock: {
			url: "/users",
			auth_url: "/auth",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	media: {
		dock: {
			url: "/media",
		},
	},
	customer: {
		plural: "customers",
		dock: {
			url: "/customers",
		},
	},
	mykart: {
		plural: "mykarts",
		dock: {
			url: "/mykart",
		},
		// bll: () => {
		//   console.log(some + `s`);
		//   return new MYBLL();
		// }
	},
	product: {
		dock: {
			url: "/products",
		},
	},
} as const;
