/**
 *
 * Autogenerated book from urn-cli
 *
 */
export const routes_book = {
	setting: {
		dock: {
			url: "/settings",
		},
	},
	customer: {
		plural: "customers",
		dock: {
			url: "/customers",
		},
	},
	mykart: {
		plural: "mykarts",
		dock: {
			url: "/mykart",
		},
		// bll: () => {
		//   console.log(some + `s`);
		//   return new MYBLL();
		// }
	},
	product: {
		dock: {
			url: "/products",
		},
	},
} as const;
