/**
 *
 * Autogenerated book from urn-cli
 *
 */
export const api_book = {
	superuser: {
		api: {
			url: "/superusers",
			auth: "/superauth",
		},
	},
	user: {
		api: {
			url: "/users",
			auth: "/auth",
		},
	},
	group: {
		api: {
			url: "/groups",
		},
	},
	error: {
		api: {
			url: "/errors",
		},
	},
	request: {
		api: {
			url: "/requests",
		},
	},
	products: {
		api: {
			url: "/products"
		}
	}
} as const;
