/**
 *
 * Autogenerated book from urn-cli
 *
 */
import { some } from "../../server/s";
import { MYBLL } from "../../server/custom";
export const bll_book = {
	superuser: {},
	user: {},
	group: {},
	error: {},
	request: {},
	mykart: {
		bll: () => {
			console.log(some);
			return new MYBLL();
		},
	},
	kart: {},
} as const;
