/**
 *
 * Autogenerated book from urn-cli
 *
 */
import * as types_202516519 from "../../lib/srv/types";
import * as hooks_815151119 from "../../lib/hooks";
import * as bll_21212 from "../../lib/api/core/bll";
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
			auth: "/superauth",
		},
	},
	user: {
		dock: {
			url: "/users",
			auth: "/auth",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
		},
	},
	mykart: {
		dock: {
			url: "/mykarts",
			auth: "/myauthkart",
			routes: {
				myroute: {
					method: types_202516519.RouteMethod.GET,
					action: types_202516519.AuthAction.READ,
					url: "/myroute",
					query: ["myq"],
					call: async (
						api_request: types_202516519.Api.Request<"mykart", "myroute">
					) => {
						console.log(api_request);
						const urn_bll_errors_api = bll_21212.basic.create("error");
						console.log(urn_bll_errors_api);
						// console.log(uranio['api']['lambda']);
						console.log(hooks_815151119);
						const urn_bll_errors = bll_21212.basic.create("error");
						return await urn_bll_errors.find_by_id("611bedc525e7b32c3f6415d8");
					},
				},
			},
		},
	},
	kart: {
		dock: {
			url: "/karts",
			routes: {
				mycustom: {
					url: "/c/:id/:date",
					query: ["sick"],
					action: types_202516519.AuthAction.READ,
					method: types_202516519.RouteMethod.GET,
					call: async (
						_api_request: types_202516519.Api.Request<"kart", "mycustom">
					) => {
						// urn_log.fn_debug(`Router Call GET [find] / [${atom_name}]`);
						const urn_bll = bll_21212.basic.create("request");
						const bll_res = await urn_bll.find_by_id(
							"611bedc525e7b32c3f6415d8"
						);
						return bll_res;
					},
				},
			},
		},
	},
} as const;
