/**
 *
 * Autogenerated book from urn-cli
 *
 */
import uranio from '../../lib/client';
import * as bll from '../../lib/api/core/bll/';
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
			auth: "/superauth",
		},
	},
	user: {
		dock: {
			url: "/users",
			auth: "/auth",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
		},
	},
	kart:{
		dock: {
			url: "/karts",
			routes: {
				mycustom: {
					url: '/c/:id/:date',
					query: ['sick'],
					action: uranio.types.AuthAction.READ,
					method: uranio.types.RouteMethod.GET,
					call: async (api_request:uranio.types.Api.Request<'request', 'mycustom'>) => {
						// urn_log.fn_debug(`Router Call GET [find] / [${atom_name}]`);
						console.log(api_request);
						const urn_bll = bll.basic.create('request');
						const bll_res = await urn_bll.find_by_id(api_request.params.id!);
						return bll_res;
					}
				}
			}
		},
	}
} as const;
