/**
 *
 * Autogenerated book from urn-cli
 *
 */
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
			auth: "/superauth",
		},
	},
	user: {
		dock: {
			url: "/users",
			auth: "/auth",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
		},
	},
	mykart: {
		dock: {
			url: "/mykarts",
			auth: "/myauthkart",
		},
	},
	product: {
		dock: {
			url: "/products",
			auth: "/proauths",
		},
	},
} as const;
