/**
 *
 * Autogenerated book from urn-cli
 *
 */
import * as types_202516519 from "../uranio/srv/types";
export const dock_book = {
	superuser: {
		dock: {
			url: "/superusers",
			auth: "/superauth",
		},
	},
	user: {
		dock: {
			url: "/users",
			auth: "/auth",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
		},
	},
	customer: {
		plural: "customers",
		dock: {
			url: "/customers",
			routes: {
				pippi: {
					method: types_202516519.RouteMethod.GET,
					action: types_202516519.AuthAction.READ,
					url: "/pippo",
					return: Number,
					call: async (
						req: types_202516519.Api.Request<"customer", "pippi">
					): Promise<number> => {
						console.log(req.route_name);
						return 899;
					},
				},
			},
		},
	},
	mykart: {
		plural: "mykarts",
		dock: {
			url: "/mykarts",
			auth: "/myauthkart",
		},
		// bll: () => {
		//   console.log(some + `s`);
		//   return new MYBLL();
		// }
	},
	product: {
		dock: {
			url: "/products",
			auth: "/proauths",
			routes: {
				myroute: {
					method: types_202516519.RouteMethod.GET,
					action: types_202516519.AuthAction.READ,
					url: "/myroute",
					call: async (
						api_request: types_202516519.Api.Request<"product", "myroute">
					): Promise<number> => {
						console.log(api_request);
						return 8;
					},
				},
			},
		},
	},
} as const;
