/**
 *
 * Autogenerated book from urn-cli
 *
 */
import * as uranio_types from "../uranio/types";
export const dock_book = {
	customer:{},
	superuser: {
		dock: {
			url: "/superusers",
			auth: "/superauth",
		},
	},
	user: {
		dock: {
			url: "/users",
			auth: "/auth",
		},
	},
	group: {
		dock: {
			url: "/groups",
		},
	},
	error: {
		dock: {
			url: "/errors",
		},
	},
	request: {
		dock: {
			url: "/requests",
		},
	},
	mykart: {
		dock: {
			url: "/mykarts",
			auth: "/myauthkart",
		},
	},
	product: {
		dock: {
			url: "/products",
			auth: "/proauths",
			routes: {
				pippo: {
					method: uranio_types.RouteMethod.GET,
					action: uranio_types.AuthAction.READ,
					url: "/pippos",
					call: async (
						api_request: uranio_types.Api.Request<"product", "pippo">
					): Promise<number> => {
						console.log(api_request);
						console.log("Pippo");
						return 7;
					},
					return: Number,
				},
				pippi2: {
					method: uranio_types.RouteMethod.GET,
					action: uranio_types.AuthAction.READ,
					url: "/pippi",
					call: async (
						api_request: uranio_types.Api.Request<"product", "pippi2">
					): Promise<number> => {
						console.log(api_request);
						console.log("Pippo3");
						return 8;
					},
					return: Number,
				},
			},
		},
	},
} as const;
