[build]
  command = "yarn generate"
  publish = "dist"

[functions]
  directory = "dist/.uranio/server/functions/"

[[redirects]]
  from = "/uranio/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [dev]
    framework = "#custom"
    command = "yarn nuxtdev"
    targetPort = 3000
    debug = true
    port = 8888
    publish = "dist"
